AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Aurora Cluster

Parameters:
  Owner:
    Description: Owner of product
    Type: String
    Default: "GARNCC"
  Product:
    Description: Name of owning product
    Type: String
    Default: "DEMO"
  Environment:
    Description: Name of Environment
    Type: String
    Default: "dev"
  DBClass:
    AllowedValues:  #just to limit me doing something stupid
    - db.t2.small
    - db.t2.medium
    - db.r4.large
    - db.r4.xlarge
    ConstraintDescription: must select a valid database instance type (db.t2small, db.m3.medium, db.m4.large).
    Description: Database instance class
    Type: String
    Default: db.t2.small
  DatabaseCluster:
    Type: String
    Description: "Aurora Database Cluster Instance"
  DBEngine:
    Description: Database engine version
    Type: String
    Default: "5.7.12"
  DBSubnetGroup:
    Description: DBSubnetGroup
    Type: String

Resources:

  ClusterInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DatabaseCluster #IMPORTANT: DO NOT CHANGE THIS ONCE THE DB HAS BEEN CREATED!!!
      DBInstanceClass: !Ref DBClass
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: aurora-mysql
      EngineVersion: !Ref DBEngine
      PubliclyAccessible: false
