AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for Artifact storage
Outputs:
  S3BucketId:
    Description: Owner S3 Bucket ID
    Value:
      Ref: Bucket

Parameters:
  BucketName:
    Description: Name of the S3 bucket.
    Type: String

Conditions:
  UseGeneratedBucketName: !Equals [!Ref BucketName, ""]

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !If [UseGeneratedBucketName, !Ref "AWS::NoValue", !Ref BucketName]
      VersioningConfiguration:
         Status: 'Enabled'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: AllPreviousVersionsToGlacier
            Status: Enabled
            NoncurrentVersionTransitions:
              - TransitionInDays: 30
                StorageClass: GLACIER
